server:
  servlet:
    context-path: /archetypemgm
logging:
  config: classpath:logback-spring.xml
  file:
    name: /opt/logs/${spring.application.name}/${spring.application.name}.log
spring:
  profiles:
    active: ${env}
    include: dao-${env},redis-${env},mgm-${env}
  application:
    name: archtype-mgm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    java:
      version: '@java.version@'
