server:
  port: ${jvm_port:8080}

spring:
  datasource:
    url: jdbc:mysql://47.93.251.190:3306/demo?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&connectTimeout=2000&socketTimeout=5000&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: 47.93.251.190
    port: 6379
    password: 123456
    database: 0
    timeout: 2000
  mail:
    host: smtp.qq.com
    port: 587
    username: liziczh@qq.com
    password: 123456
    default-encoding: UTF-8
    test-connection: false
  kafka:
    init:
      create-topics: testTopic
      partition-num: 2
      replication-factor: 1
    producer:
      bootstrap-servers: 47.93.251.190:9092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 47.93.251.190:9092
      group-id: testGroup
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


ref:
  service: localhost